[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "linker=C:\\ProgramData\\mingw-dual\\mingw64\\bin\\x86_64-w64-mingw32-gcc.exe"]

[target.i686-pc-windows-gnu]
rustflags = ["-C", "linker=C:\\ProgramData\\mingw-dual\\mingw32\\bin\\i686-w64-mingw32-gcc.exe"]
