[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "linker=aarch64-linux-gnu-gcc"]

[target.arm-unknown-linux-gnueabi]
rustflags = ["-C", "linker=arm-none-eabi-gcc"]

[target.powerpc64-unknown-linux-gnu]
rustflags = ["-C", "linker=powerpc64-linux-gnu-gcc"]
