name: build natives (unix)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Install GCC
      run: pacman --disable-sandbox --noconfirm -Sy gcc aarch64-linux-gnu-gcc
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew :platform:unix:build

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: platform/unix/build/
