
name: build natives (windows)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Install 7-Zip
      uses: crazy-max/ghaction-chocolatey@v3
      with:
        args: install 7zip --no-progress

    - name: Set up MinGW
      shell: pwsh
      run: |
        .\install-mingw-dual.ps1

    - name: Set up Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable-x86_64-pc-windows-gnu
        cache: false
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
  
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew :platform:windows:build

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: platform/windows/build/
